LOCAL_PATH := $(call my-dir)

SOURCE_AQUAMAIL_PATH := $(LOCAL_PATH)

include $(CLEAR_VARS)
LOCAL_MODULE := AquaMail

LOCAL_OVERRIDES_PACKAGES := \
    Email \
    Exchange2 \
    Exchange

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED

BUILD_AQUAMAIL := $(info $(shell bash $(SOURCE_AQUAMAIL_PATH)/aquamail.sh $(LOCAL_PATH) 1>&2))

LOCAL_SRC_FILES := AquaMail.apk

include $(BUILD_PREBUILT)
